### ISSUE TITLE
Implements results

### ISSUE THREAD

**Issue by xujli** [xyfJASON/Repro-Federated-Learning#1]
I ran your code without changing parameters, the accuracy of fedmix and naive are around 41%. Changing beta in config.yml of FedAvg to 0.1, the accuracy of FedAvg is above 46%.

**Comment by xyfJASON** [comment]
Thanks for your comment! If you want to compare between different algorithms, it's better to use the **exactly same** data partitions rather than dividing the data randomly at each run. You can do this by running FedAvg with the following configuration first:
```
partition:
  choice: Dirichlet
  Dirichlet:
    beta: 0.1
```
Then a file `idx_parties.txt` will be saved in log directory. You can move it to wherever you like, and run FedMix with the following configuration:
```
partition:
  choice: read_from_file
  read_from_file:
    file_path: <path to idx_parites.txt>
```
So that FedMix will use the exactly same data partitions as FedAvg.

---

I did all the comparisons in this way, and the results of FedAvg and FedMix should be comparable. However, please note that I still can't make FedMix consistently better than FedAvg, which I've stated in README file.
